### PR TITLE
Remove future_parser setting

### PR DESCRIPTION
**Pull request by DavidS**
Puppet 4 doesn't have a future parser. It IS the future!

### CODE REVIEW

**Comment by logicminds** [comment]
I have actually gutted all this in an upcoming release which relies solely on puppet 4 parser.  Time has been in the way of releasing it.  I would expect this to be completed in early April.  The auto generated test coverage is way better too.

**Comment by DavidS** [comment]
Nice, looking forward to that! Do you have that code up somewhere for testing? I've been trying the future branch, which very little success.

**Comment by logicminds** [comment]
just forced pushed the updated code to the future branch.   Beware, demons be present. Feel free to review code and tell me how it could be better.

**Comment by DavidS** [comment]
Until this can be fully resolved, one thing that worked for me is replacing puppet 3's vendored `safe_yaml` with the upstream version. AFAICT this is only used for network communication, which retrospec isn't using anyways. This only required a bit of futzing around in lib/puppet/vendor.

**Comment by logicminds** [comment]
Because this gem brings its own puppet version, I don't have to concern myself with which puppet version you are using.  The only reason why you would want to use the future parser setting is to allow the vendored puppet version `3.7.3` to be able to parse your code written in puppet 4 language.  

I would also recommend installing puppet-retrospec outside of your Gemfile since it would be considered 'universal'.  But I could see how things might get hairy if using a ruby not supported by puppet-3.7.

**Comment by DavidS** [comment]
It seems to be enough to have ruby-safe-yaml from debian installed to avoid puppet's vendored version. Of course that all is hackery that is not recommended for production, but Works for Me[tm] to unblock me for more Saturday night fun.

**Comment by logicminds** [comment]
@DavidS hit me up on IRC (cosman)

**Pull request closed without merging**
