### PR TITLE
issue28: pass correct git ref

### LINKED ISSUE #28: handle symlinks in the templates directory correctly
Currently retrospect does not copy over symlinks.  For items like pre-commit hooks that could reference a hook elsewhere we will want to copy the symlink directly.

### PR DESCRIPTION
**Pull request by witjoh**
fixes #28

### CODE REVIEW

**Comment by witjoh** [comment]
works for me.  If i remove the repo in ~/retrospecs/repos, the correct branch is now checked out.
travis is bailing out on the bundler commend

**Comment by logicminds** [comment]
This repo is actually a mirror since I keep everything in gitlab and use gitlab ci.  I need to figure out how to gitlab ci work with github.  Or just redirect this repo to my gitlab site.

**Comment by witjoh** [comment]
any idea when a new release will be published ?

**Comment by logicminds** [comment]
Soon very soon. Lots of new updates!

**Comment by witjoh** [comment]
Thx for the merge
If I can help with something ?

**Comment by logicminds** [comment]
Any kind of documentation, blog article, tweeting about this tool, tell people, create issues that you find.

**Pull request merged**
